---
title       : Matrix Exploratory Data Analysis
subtitle    : MEDA
author      : Neurodata
job         : 
framework   : html5slides   # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : draft # {standalone, draft}
knit        : slidify::knit2slides #
---

```{r, echo=FALSE, eval=FALSE}
require(slidify)
require(rmarkdown)
render('singles.Rmd')
system('open singles.html')
#slidify::knit2slides("index.Rmd")
```

# Kristina15 Single Figures

### This set is a run with a sample of size 1000 using various seeds for randomization

#### Stacked Level mean plots (Seed 1234)
- [6.4 Raw: Seed 1234](examples/Kristina15/figs/k15Raw_seed1234.png)  
- [6.4 Log: Seed 1234](examples/Kristina15/figs/k15Log_seed1234.png)  
- [6.4 01e3: Seed 1234](examples/Kristina15/figs/k1501e3_seed1234.png)  

#### Stacked Level mean plots (Seed 317)
- [6.4 Raw: Seed 317](examples/Kristina15/figs/k15Raw_seed317.png)  
- [6.4 Log: Seed 317](examples/Kristina15/figs/k15Log_seed317.png)
- [6.4 01e3: Seed 317](examples/Kristina15/figs/k1501e3_seed317.png)  

---

### This set is a run with a sample of size 10000 using various seeds for randomization

#### Stacked Level mean plots (Seed 1234)
- [6.4 Raw: Seed 1234](examples/Kristina15/figs/k15Raw_seed1234_size10000.png)  
- [6.4 Log: Seed 1234](examples/Kristina15/figs/k15Log_seed1234_size10000.png)  
- [6.4 01e3: Seed 1234](examples/Kristina15/figs/k1501e3_seed1234_size10000.png)  

#### Stacked Level mean plots (Seed 317)
- [6.4 Raw: Seed 317](examples/Kristina15/figs/k15Raw_seed317_size10000.png)  
- [6.4 Log: Seed 317](examples/Kristina15/figs/k15Log_seed317_size10000.png)
- [6.4 01e3: Seed 317](examples/Kristina15/figs/k1501e3_seed317_size10000.png)  

---

# Weiler Single Figures

### This set is a run with a sample of size 1000 using various seeds for randomization

#### Stacked Level mean plots (Seed 1234)
- [6.4 Raw: Seed 1234](examples/Weiler/figs/weilerRaw_seed1234.png)  
- [6.4 Log: Seed 1234](examples/Weiler/figs/weilerLog_seed1234.png)  
- [6.4 01e3: Seed 1234](examples/Weiler/figs/weiler01e3_seed1234.png)  

#### Stacked Level mean plots (Seed 317)
- [6.4 Raw: Seed 317](examples/Weiler/figs/weilerRaw_seed317.png)  
- [6.4 Log: Seed 317](examples/Weiler/figs/weilerLog_seed317.png)  
- [6.4 01e3: Seed 317](examples/Weiler/figs/weiler01e3_seed317.png)  

--- 

### This set is a run with a sample of size 10000 using various seeds for randomization

#### Stacked Level mean plots (Seed 1234)
- [6.4 Raw: Seed 1234](examples/Weiler/figs/weilerRaw_seed1234_size10000.png)  
- [6.4 Log: Seed 1234](examples/Weiler/figs/weilerLog_seed1234_size10000.png)  
- [6.4 01e3: Seed 1234](examples/Weiler/figs/weiler01e3_seed1234_size10000.png)  

#### Stacked Level mean plots (Seed 317)
- [6.4 Raw: Seed 317](examples/Weiler/figs/weilerRaw_seed317_size10000.png)  
- [6.4 Log: Seed 317](examples/Weiler/figs/weilerLog_seed317_size10000.png)  
- [6.4 01e3: Seed 317](examples/Weiler/figs/weiler01e3_seed317_size10000.png)  

---
---
---
